model:
  name: meta-llama/Llama-3.2-1B
  batch_size: 8
  max_length: 512

processing:
  chunk_size: 1000
  overlap: 200

neo4j:
  uri: bolt://localhost:7687
  user: neo4j
  password: password

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: knowledge_graph.log
